sudo: true
dist: focal
addons:
language: node_js
node_js:
    - "18"
before_script:
    - npm run lint
    - npm run cpd
after_script:
    - npm run coveralls
git:
    depth: 10
cache:
    yarn: true
